language: python
python:
    - "2.7"
install:
    - "pip install platformio"
    - "pip install coveralls"
    - "pip install --upgrade pip"
    - "pip install .[test]"
script: "nosetests --with-coverage --cover-package=openag"
after_success: coveralls
